"""initial schema

Revision ID: ce4ed1952544
Revises: 
Create Date: 2026-08-03 11:43:52.040710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ce4ed1952544'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('initiatives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('KBI', 'PLATFORM', 'RECURRING_OPS', name='initiative_type'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('business_goal', sa.Text(), nullable=True),
    sa.Column('jira_number', sa.String(length=50), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('expected_delivery_date', sa.Date(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='priority'), nullable=True),
    sa.Column('complexity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='complexity'), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'ARCHIVED', name='initiative_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_initiative_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_upgrade_type', sa.Boolean(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ai_breakdown_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiative_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('raw_response_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('initiative_engineers',
    sa.Column('initiative_id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('opted_in_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.PrimaryKeyConstraint('initiative_id', 'engineer_id')
    )
    op.create_table('platform_initiative_details',
    sa.Column('initiative_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['platform_initiative_categories.id'], ),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.PrimaryKeyConstraint('initiative_id')
    )
    op.create_table('recurring_ops_details',
    sa.Column('initiative_id', sa.Integer(), nullable=False),
    sa.Column('recurrence_type', sa.Enum('ANNUAL', 'QUARTERLY', 'MONTHLY', 'WEEKLY', 'AD_HOC', name='recurrence_type'), nullable=False),
    sa.Column('recurrence_interval', sa.Integer(), nullable=False),
    sa.Column('anchor_month', sa.Integer(), nullable=True),
    sa.Column('anchor_day', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.PrimaryKeyConstraint('initiative_id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiative_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('stage', sa.Enum('HLD', 'LLD', 'SOLUTION_DESIGN_APPROVAL', 'NON_PROD_DEPLOYMENT', 'PROD_DEPLOYMENT', 'OTHER', name='task_stage'), nullable=True),
    sa.Column('owner_engineer_id', sa.Integer(), nullable=False),
    sa.Column('forecast_duration_days', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'BLOCKED', 'COMPLETE', name='task_status'), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.ForeignKeyConstraint(['owner_engineer_id'], ['engineers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upgrade_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('initiative_id', sa.Integer(), nullable=False),
    sa.Column('system_name', sa.String(length=200), nullable=False),
    sa.Column('system_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETE', 'SKIPPED', name='upgrade_unit_status'), nullable=False),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['initiative_id'], ['initiatives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('time_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('engineer_id', sa.Integer(), nullable=False),
    sa.Column('week_start_date', sa.Date(), nullable=False),
    sa.Column('fiscal_year_label', sa.String(length=10), nullable=False),
    sa.Column('hours', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['engineer_id'], ['engineers.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'week_start_date', name='uq_time_entry_task_week')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('time_entries')
    op.drop_table('upgrade_units')
    op.drop_table('tasks')
    op.drop_table('recurring_ops_details')
    op.drop_table('platform_initiative_details')
    op.drop_table('initiative_engineers')
    op.drop_table('ai_breakdown_requests')
    op.drop_table('platform_initiative_categories')
    op.drop_table('initiatives')
    op.drop_table('engineers')
    # ### end Alembic commands ###
